SELECT  [Order_ID]     
      ,[Customer_Type]
      ,[Product]
      ,[Category]      
      ,[Quantity]
      ,[Discount]
      ,[Total_Price]
      ,[Region]
      ,[Order_Date]
  FROM [abde_dz].[dbo].[synthetic_beverage_sales_data]
